export const CHANGE_SEARCH_FIELD= 'CHANGE_SEARCH_FIELD';

export const REQUEST_PHOTO_PENDING = 'REQUEST_PHOTO_PENDING';
export const REQUEST_PHOTO_SUCCESS = 'REQUEST_PHOTO_SUCCESS';
export const REQUEST_PHOTO_FAILED = 'REQUEST_PHOTO_FAILED';
